- name: Configure this system to run IoT Demo
  hosts: demos
  connection: local
  tasks:
      - name: Clone Business Rules code from github
        git: repo=https://github.com/MichaelFitzurka/IoT_Demo_BusinessRules.git
             dest=./../IoT_Demo_BusinessRules force=yes
        tags:
         - github

      - name: Clone Smart Gateway code from github
        git: repo=https://github.com/MichaelFitzurka/IoT_Demo_Gateway.git
             dest=./../IoT_Demo_Gateway force=yes
        tags:
         - github

      - name: Clone Smart Datacenter code from github
        git: repo=https://github.com/MichaelFitzurka/IoT_Demo_Datacenter.git
             dest=./../IoT_Demo_Datacenter force=yes
        tags:
         - github

      - name: Clone Sensor code from github
        git: repo=https://github.com/MichaelFitzurka/IoT_Demo_Sensors.git
             dest=./../IoT_Demo_Sensors force=yes
        tags:
         - github


      - name: Copy JBoss EAP for Datacenter images if exists
        copy: src=./../software/jboss-eap-7.0.0.zip dest=../IoT_Demo_Datacenter/bpm/Docker_Files/software/
        tags:
         - copy_applications

      - name: Copy JBoss EAP patch for Datacenter images if exists
        copy: src=./../software/jboss-eap-7.0.3-patch.zip dest=../IoT_Demo_Datacenter/bpm/Docker_Files/software/
        tags:
         - copy_applications

      - name: Copy JBoss BPM if exists
        copy: src=./../software/jboss-bpmsuite-6.4.0.GA-deployable-eap7.x.zip dest=../IoT_Demo_Datacenter/bpm/Docker_Files/software/
        tags:
         - copy_applications

      - name: Copy JBoss DataGrid Libraries for EAP if exists
        copy: src=./../software/jboss-datagrid-7.0.0-eap-modules-library.zip dest=../IoT_Demo_Datacenter/bpm/Docker_Files/software/
        tags:
         - copy_applications

      - name: Copy JBoss Fuse if exists
        copy: src=./../software/jboss-fuse-karaf-6.3.0.redhat-187.zip dest=../IoT_Demo_Datacenter/Fuse/Docker_Files/software/
        tags:
         - copy_applications

      - name: Copy JBoss DataGrid if exists
        copy: src=./../software/jboss-datagrid-7.0.0-server.zip dest=../IoT_Demo_Datacenter/DataGrid/Docker_Files/software/
        tags:
         - copy_applications
